Updated certain variable names
GemueseHasser/JumpAndRun pull request #6
Opened 2024-03-12 15:06 UTC by TheBoringEdward

Many of the variables used by the opponents are either misleading or outdated, which has been rectified within this branch .

Due to this branch originally being intended to implement a sort of jump-pad, said jump-pad can be found as a new opponent-type, although, other than having a different texture and name, being functionally identical to the already existing barriers.

@GemueseHasser , please verify first that this pull will not bugger something up within the master branch.

2024-03-12 16:04 UTC, GemueseHasser requested changes

2024-03-12 16:04 UTC, GemueseHasser commented on src/de/informatik/game/object/map/opponent/Barrier.java
> +        if (!isBackgroundMoving) return;
we should not rename the isBackgroundMovable variable to isBackgroundMoving as this name would be incorrect.

2024-03-12 16:04 UTC, GemueseHasser commented on src/de/informatik/game/object/map/opponent/Barrier.java
> +        if (!isBackgroundMoving) return;
we should not rename the isBackgroundMovable variable to isBackgroundMoving as this name would be incorrect.

2024-03-12 16:04 UTC, GemueseHasser commented on src/de/informatik/game/constant/OpponentType.java
> +    JUMPPAD(Jumppad.class);
we should also write documentation for this new enum value.

2024-03-12 16:04 UTC, GemueseHasser commented on src/de/informatik/game/constant/ImageType.java
> +    JUMPPAD("jumppad.png");
we should also write documentation for this new enum value.

2024-03-12 16:04 UTC, GemueseHasser commented on src/de/informatik/game/object/map/opponent/Jumppad.java
It basically belongs to Javadoc about the class, all variables and all methods that are not overridden. In addition, all constant variables and all local variables should be ordered and enclosed in an editor fold. Two paragraphs should be inserted between each block consisting of variables. Likewise, all implemented methods should be enclosed in an editor fold. Each class should end with a blank line.

2024-03-14 16:00 UTC, TheBoringEdward commented on src/de/informatik/game/object/map/opponent/Jumppad.java
I have no clue how to fix that one.

2024-03-14 16:01 UTC, TheBoringEdward commented on src/de/informatik/game/object/map/opponent/Barrier.java
> +        if (!isBackgroundMoving) return;
Reverted

2024-03-14 16:01 UTC, TheBoringEdward commented on src/de/informatik/game/object/map/opponent/Barrier.java
> +        if (!isBackgroundMoving) return;
Reverted

2024-03-14 16:02 UTC, TheBoringEdward commented on src/de/informatik/game/constant/OpponentType.java
> +    JUMPPAD(Jumppad.class);
Added

2024-03-14 16:02 UTC, TheBoringEdward commented on src/de/informatik/game/constant/ImageType.java
> +    JUMPPAD("jumppad.png");
Added

2024-03-14 16:44 UTC, TheBoringEdward commented on src/de/informatik/game/object/map/opponent/Jumppad.java
I think I resolved it now....

2024-03-14 17:01 UTC, TheBoringEdward commented on src/de/informatik/game/object/map/opponent/Jumppad.java
Now perhaps..?

2024-03-14 21:33 UTC, GemueseHasser approved these changes

2024-03-14 21:33 UTC, merged